### ISSUE TITLE
Smoke tests failing on macos-arm64 runners

### ISSUE THREAD

**Issue by atalman** [pytorch/test-infra#4342]
Here is the workflow : https://github.com/pytorch/audio/actions/runs/5463753972/jobs/9944856131

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |         openblas          10 KB
    gmp-6.2.1                  |       hc377ac9_3         437 KB
    gmpy2-2.1.2                |  py310h8c48613_0         152 KB
    libgfortran-5.0.0          |11_3_0_hca03da5_28         142 KB
    libgfortran5-11.3.0        |      h009349e_28         1.0 MB
    libopenblas-0.3.21         |       h269037a_0         3.3 MB
    llvm-openmp-14.0.6         |       hc6e5704_0         253 KB
    mpc-1.1.0                  |       h8c48613_1         104 KB
    mpfr-4.0.2                 |       h695f6f0_1         423 KB
    mpmath-1.2.1               |  py310hca03da5_0         778 KB
    networkx-2.8.4             |  py310hca03da5_1         2.7 MB
    numpy-1.25.0               |  py310h3b2db8e_0          13 KB
    numpy-base-1.25.0          |  py310ha9811e2_0         5.8 MB
    pytorch-2.1.0.dev20230705  |         py3.10_0        49.2 MB  pytorch-nightly
    sympy-1.11.1               |  py310hca03da5_0        11.8 MB
    torchaudio-2.1.0.dev20230705|        py310_cpu         5.3 MB  file:///Users/ec2-user/runner/_work/audio/audio/pytorch/audio/distr
    typing_extensions-4.6.3    |  py310hca03da5_0          53 KB
    ------------------------------------------------------------
                                           Total:        81.5 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/osx-arm64::blas-1.0-openblas 
  filelock           pkgs/main/osx-arm64::filelock-3.9.0-py310hca03da5_0 
  gmp                pkgs/main/osx-arm64::gmp-6.2.1-hc377ac9_3 
  gmpy2              pkgs/main/osx-arm64::gmpy2-2.1.2-py310h8c48613_0 
  jinja2             pkgs/main/osx-arm64::jinja2-3.1.2-py310hca03da5_0 
  libcxx             pkgs/main/osx-arm64::libcxx-14.0.6-h848a8c0_0 
  libgfortran        pkgs/main/osx-arm64::libgfortran-5.0.0-11_3_0_hca03da5_28 
  libgfortran5       pkgs/main/osx-arm64::libgfortran5-11.3.0-h009349e_28 
  libopenblas        pkgs/main/osx-arm64::libopenblas-0.3.21-h269037a_0 
  llvm-openmp        pkgs/main/osx-arm64::llvm-openmp-14.0.6-hc6e5704_0 
  markupsafe         pkgs/main/osx-arm64::markupsafe-2.1.1-py310h1a28f6b_0 
  mpc                pkgs/main/osx-arm64::mpc-1.1.0-h8c48613_1 
  mpfr               pkgs/main/osx-arm64::mpfr-4.0.2-h695f6f0_1 
  mpmath             pkgs/main/osx-arm64::mpmath-1.2.1-py310hca03da5_0 
  networkx           pkgs/main/osx-arm64::networkx-2.8.4-py310hca03da5_1 
  numpy              pkgs/main/osx-arm64::numpy-1.25.0-py310h3b2db8e_0 
  numpy-base         pkgs/main/osx-arm64::numpy-base-1.25.0-py310ha9811e2_0 
  pytorch            pytorch-nightly/osx-arm64::pytorch-2.1.0.dev202[307](https://github.com/pytorch/audio/actions/runs/5463753972/jobs/9944856131#step:13:308)05-py3.10_0 
  pyyaml             pkgs/main/osx-arm64::pyyaml-6.0-py[310](https://github.com/pytorch/audio/actions/runs/5463753972/jobs/9944856131#step:13:311)h80987f9_1 
  sympy              pkgs/main/osx-arm64::sympy-1.11.1-py310hca03da5_0 
  torchaudio         distr/osx-arm64::torchaudio-2.1.0.dev20230705-py310_cpu 
  typing_extensions  pkgs/main/osx-arm64::typing_extensions-4.6.3-py310hca03da5_0 
  yaml               pkgs/main/osx-arm64::yaml-0.2.5-h1a28f6b_0 


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

+ [[ ! -f pytorch/audio/test/smoke_test/smoke_test.py ]]
pytorch/audio/test/smoke_test/smoke_test.py found
+ echo 'pytorch/audio/test/smoke_test/smoke_test.py found'
+ conda run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_5463753972_smoke python3 pytorch/audio/test/smoke_test/smoke_test.py
+ local cmd=run
+ case "$cmd" in
+ __conda_exe run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_5463753972_smoke python3 pytorch/audio/test/smoke_test/smoke_test.py
+ /opt/homebrew/Caskroom/miniconda/base/bin/conda run -p /Users/ec2-user/runner/_work/_temp/pytorch_pkg_helpers_5463753972_smoke python3 pytorch/audio/test/smoke_test/smoke_test.py
Traceback (most recent call last):
  File "/Users/ec2-user/runner/_work/audio/audio/pytorch/audio/test/smoke_test/smoke_test.py", line 45, in <module>
    main()
  File "/Users/ec2-user/runner/_work/audio/audio/pytorch/audio/test/smoke_test/smoke_test.py", line 28, in main
    base_smoke_test()
  File "/Users/ec2-user/runner/_work/audio/audio/pytorch/audio/test/smoke_test/smoke_test.py", line 7, in base_smoke_test
    import torchaudio  # noqa: F401
ModuleNotFoundError: No module named 'torchaudio'

ERROR conda.cli.main_run:execute(47): `conda run python3 pytorch/audio/test/smoke_test/smoke_test.py` failed. (See above for error)
Error: Process completed with exit code 1.
```

This is happening for both conda and wheels.  There is a conflict with already installed torch.
This can be mitigated by doing before executing smoke tests:
```
pip3 uninstall -y torch torchaudio torchvision
```

**Comment by atalman** [comment]
Looks like the issue is that which python3 in coda environment give wrong python3 path
