### ISSUE TITLE
hud.pytorch.org/metrics fails to display the metrics page

### ISSUE THREAD

**Issue by DanilBaibak** [pytorch/test-infra#4784]
Application error: a client-side exception has occurred (see the browser console for more information):
```
framework-81da43a8dcd978d9.js:1 Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"count":7,"avg_queue_s":28720,"machine_type":null}
    at 374-25d1e2fca035ac6e.js:1:114357
    at jo (374-25d1e2fca035ac6e.js:1:114568)
    at zo (374-25d1e2fca035ac6e.js:1:114706)
    at $o (374-25d1e2fca035ac6e.js:1:115215)
    at ft (374-25d1e2fca035ac6e.js:1:38674)
    at Qo (374-25d1e2fca035ac6e.js:1:119456)
    at 374-25d1e2fca035ac6e.js:28:58586
    at go (framework-81da43a8dcd978d9.js:1:62695)
    at bu (framework-81da43a8dcd978d9.js:1:82109)
    at di (framework-81da43a8dcd978d9.js:1:122133)
```

**Comment by DanilBaibak** [comment]
This is where the error comes from - https://github.com/pytorch/test-infra/blob/main/tools/torchci/queue_alert.py#L77

**Comment by DanilBaibak** [comment]
I went a bit deeper and found that query [queued_jobs.sql](https://github.com/pytorch/test-infra/blob/main/torchci/rockset/metrics/__sql/queued_jobs.sql) returns null for the machine_type filed.

<img width="766" alt="Screenshot 2023-12-06 at 10 33 31" src="https://github.com/pytorch/test-infra/assets/3964975/9fb45ed6-8510-4654-ae45-40d366b2d415">
