### ISSUE TITLE
xpu: support torch.utils.data.DataLoader(pin_memory_device='xpu')

### ISSUE THREAD

**Issue by dvrogozh** [pytorch/test-infra#5211]
`torch.utils.data.DataLoader(pin_memory_device='xpu')` is currently not supported with upstream PyTorch XPU backend. I know that with IPEX this feature was supported. Please, support the feature if it's relevant for XPU or update PyTorch documentation with optimization notice that feature is not needed for XPU.

Relevant environment:
* torch - https://github.com/pytorch/pytorch/commit/a0429c01ad665ffb2faa04a411913ecee9962566
* torchvision - https://github.com/pytorch/vision/commit/947ae1dc71867f28021d5bc0ff3a19c249236e2a

This can be reproduced with:
```
$ cat data_loader_mempin.py
import torch
import torchvision

print('torch.__version__:' + torch.__version__)
print('torch.xpu.is_available(): ' + str(torch.xpu.is_available()))

dataset = torchvision.datasets.FakeData(size=10, transform=torchvision.transforms.ToTensor())
loader = torch.utils.data.DataLoader(dataset, pin_memory=True, pin_memory_device='xpu')

with torch.inference_mode():
    for batch_idx, (sample, target) in enumerate(loader):
        print(batch_idx)
        print(sample.is_pinned())
```
Gives this output:
```
$ python3 data_loader_mempin.py
torch.__version__:2.4.0a0+gita0429c0
torch.xpu.is_available(): True
Traceback (most recent call last):
  File "/home/dvrogozh/tests/data_loader_mempin.py", line 11, in <module>
    for batch_idx, (sample, target) in enumerate(loader):
  File "/home/dvrogozh/git/pytorch/pytorch/torch/utils/data/dataloader.py", line 629, in __next__
    data = self._next_data()
  File "/home/dvrogozh/git/pytorch/pytorch/torch/utils/data/dataloader.py", line 674, in _next_data
    data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)
  File "/home/dvrogozh/git/pytorch/pytorch/torch/utils/data/_utils/pin_memory.py", line 88, in pin_memory
    clone[i] = pin_memory(item, device)
  File "/home/dvrogozh/git/pytorch/pytorch/torch/utils/data/_utils/pin_memory.py", line 58, in pin_memory
    return data.pin_memory(device)
NotImplementedError: The operator 'aten::_pin_memory' is not currently implemented for the XPU device. Please open a feature on https://github.com/intel/torch-xpu-ops/issues. You can set the environment variable `PYTORCH_ENABLE_XPU_FALLBACK=1` to use the CPU implementation as a fallback for XPU unimplemented operators. WARNING: this will bring unexpected performance compared with running natively on XPU.
```

**Comment by dvrogozh** [comment]
Filed https://github.com/intel/torch-xpu-ops/issues/261 as requested in console output of the sample I've attached.

**Comment by dvrogozh** [comment]
I just noticed that I accidentally opened this issue in a wrong repo. Created https://github.com/pytorch/pytorch/issues/126491 in a correct location. I am sorry for inconvenience.
