### ISSUE TITLE
Update S3 HTML indices for download.pytorch.org for libtorch failing since #5296

### ISSUE THREAD

**Issue by clee2000** [pytorch/test-infra#5304]
The Update S3 HTML indices for download.pytorch.org action failed to upload the indices for libtorch (added #5296). The gha_workflow_s3_update role for the pytorch aws account doesn't have access to the libtorch key in the pytorch bucket.
I'm not sure how the gha_workflow_s3_update role gets set

https://github.com/pytorch/test-infra/actions/workflows/update-s3-html.yml
Ex https://github.com/pytorch/test-infra/actions/runs/9404574523
```
+ python s3_management/manage.py libtorch
Traceback (most recent call last):
  File "/__w/test-infra/test-infra/s3_management/manage.py", line 549, in <module>
INFO: Uploading indices for 'libtorch'
    main()
DEBUG: Fetched 3365 objects for 'libtorch' in 20.27 seconds
  File "/__w/test-infra/test-infra/s3_management/manage.py", line 543, in main
    idx.upload_libtorch_html()
  File "/__w/test-infra/test-infra/s3_management/manage.py", line 366, in upload_libtorch_html
    ).put(
      ^^^^
  File "/opt/conda/lib/python3.11/site-packages/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/boto3/resources/action.py", line [88](https://github.com/pytorch/test-infra/actions/runs/9404574523/job/25903782617#step:5:89), in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line [98](https://github.com/pytorch/test-infra/actions/runs/9404574523/job/25903782617#step:5:99)3, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
INFO Uploading libtorch/cu[101](https://github.com/pytorch/test-infra/actions/runs/9404574523/job/25903782617#step:5:102)/index.html
Error: Process completed with exit code 1.
```

cc @atalman @malfet

**Comment by huydhn** [comment]
@malfet: Testing this change is tricky without actual deployment to prod

**Comment by malfet** [comment]
Was fixed by https://www.internalfb.com/intern/diff/D58477984 (adjusted permissions to allow workflow modify html files in libtorch folder
