### ISSUE TITLE
hud.pytorch.org/metrics fails to render metrics

### ISSUE THREAD

**Issue by malfet** [pytorch/test-infra#981]
With `Application error`:  a client-side exception has occurred (see the browser console for more information).
And exception in dev console shows the following:
```
main-56026c721a4abe59.js:1 Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"count":5,"avg_queue_s":1667,"machine_type":null}
    at 993-3bc1f63b8d14f1f8.js:1:174013
    at Ml (993-3bc1f63b8d14f1f8.js:1:174224)
    at El (993-3bc1f63b8d14f1f8.js:1:174362)
    at Dl (993-3bc1f63b8d14f1f8.js:1:174871)
    at ft (993-3bc1f63b8d14f1f8.js:1:66379)
    at _l (993-3bc1f63b8d14f1f8.js:1:179112)
    at 993-3bc1f63b8d14f1f8.js:28:58016
    at go (framework-81da43a8dcd978d9.js:1:62695)
    at bu (framework-81da43a8dcd978d9.js:1:82109)
    at di (framework-81da43a8dcd978d9.js:1:122133)
```

**Comment by kit1980** [comment]
Did you select something specific in the drop-downs?
The https://hud.pytorch.org/metrics site works fine for me currently, I tried different selections and also logged in/out.

**Comment by malfet** [comment]
Interesting, it works now as well... Closing as I have no idea how to repro it any more
